language: r
compiler:
 - gcc

before_install:
 - sh travis/install-mpi.sh mpich2
 - git clone git://github.com/elemental/Elemental.git
 - cd Elemental
 - mkdir build && cd build
 - cmake .. -DCMAKE_INSTALL_PREFIX=~/local/El;
 - make -j2 && sudo make install